version: '3'
services:
  redis:
    image: redis:7
    ports:
      - 6379:6379

  celery_app:
    build:
      context: .
    image: celery_app

  celery_beat:
    image: celery_app
    depends_on:
      - redis
    command: celery -A app.main:app beat --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  celery_worker:
    image: celery_app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_WORKER_CONCURRENCY=2
    depends_on:
      - redis
    command: celery -A app.main:app worker --loglevel=info
